import { buildAppCreatorPlan, type AppCreatorInput, type AppCreatorPlan } from "@/lib/app-creator";
import { queueCliRunnerJob } from "@/lib/cli-runner-jobs";

export interface AppForgeRepoHandoffInput extends AppCreatorInput {
  owner?: string | null;
  visibility?: "private" | "public";
}

export interface AppForgeRepoHandoffResult {
  ok: boolean;
  appPlan: AppCreatorPlan;
  repo: string;
  repoName: string;
  visibility: "private" | "public";
  files: Array<{ path: string; purpose: string }>;
  commands: string[];
  safety: string;
  message: string;
  nextAction: string;
}

function cleanRepoName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "rune-generated-app";
}

function ownerOrDefault(owner?: string | null) {
  return (owner || process.env.RUNE_GITHUB_OWNER || "Tanjiro-1122").trim();
}

export function createAppForgeRepoHandoff(input: AppForgeRepoHandoffInput): AppForgeRepoHandoffResult {
  const appPlan = buildAppCreatorPlan(input);
  const repoName = cleanRepoName(input.repo?.split("/").pop() || appPlan.slug);
  const owner = ownerOrDefault(input.owner || input.repo?.split("/")[0]);
  const visibility = input.visibility || "private";
  const repo = `${owner}/${repoName}`;
  const folder = `generated/${repoName}`;

  const files = [
    { path: "package.json", purpose: "App scripts and dependencies" },
    { path: "src/App.tsx", purpose: "Generated starter UI" },
    { path: "src/main.tsx", purpose: "React entrypoint" },
    { path: "src/index.css", purpose: "Premium clean styling" },
    { path: "README.md", purpose: "Project description, safety notes, and next steps" },
  ];

  const commands = [
    `mkdir -p ${folder}`,
    `gh repo create ${repo} --${visibility} --description "${appPlan.appName} generated by Rune App Forge v1"`,
    `cd ${folder}`,
    "npm install",
    "npm run build",
    `git remote add origin git@github.com:${repo}.git`,
    "git checkout -b initial-app-forge-scaffold",
    "git add . && git commit -m \"Initial Rune App Forge scaffold\"",
    "git push -u origin initial-app-forge-scaffold",
  ];

  return {
    ok: true,
    appPlan,
    repo,
    repoName,
    visibility,
    files,
    commands,
    safety: "repo_handoff_only_no_repo_created_no_files_written_no_deploy",
    message: "App Forge v1 prepared a new-repo handoff plan. It did not create a GitHub repo, write files, deploy, merge, mutate schemas, or touch production.",
    nextAction: "Approve a follow-up trusted runner job to create the repo and generate the scaffold, or ask Rune to refine the app plan first.",
  };
}


export const APP_FORGE_REPO_CREATE_APPROVAL_PHRASE = "APPROVE APP FORGE REPO CREATE";

export interface QueueAppForgeRepoCreateInput extends AppForgeRepoHandoffInput {
  approvalText: string;
  workspaceId?: string | null;
  conversationId?: string | null;
}

function encodeMetadata(metadata: Record<string, unknown>) {
  return Buffer.from(JSON.stringify(metadata), "utf8").toString("base64url");
}

export async function queueAppForgeRepoCreate(input: QueueAppForgeRepoCreateInput) {
  const handoff = createAppForgeRepoHandoff(input);
  if (input.approvalText !== APP_FORGE_REPO_CREATE_APPROVAL_PHRASE) {
    return {
      ok: false as const,
      handoff,
      requiredApprovalPhrase: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
      error: "Exact approval phrase is required before queuing App Forge repo creation.",
      safety: "approval_required_no_repo_created_no_files_written_no_deploy",
    };
  }

  const metadata = {
    appForgeVersion: 2,
    repo: handoff.repo,
    repoName: handoff.repoName,
    visibility: handoff.visibility,
    appName: handoff.appPlan.appName,
    appPlan: handoff.appPlan,
    coreFeatures: handoff.appPlan.coreFeatures,
    screens: handoff.appPlan.screens,
    approval_text: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
    publicLaunch: false,
    deploy: false,
    merge: false,
    schemaMutation: false,
    paymentsChange: false,
    customerFacing: false,
    safety: "queued_repo_create_branch_push_no_deploy_no_merge_no_schema_mutation",
  };
  const command = `npm run app-forge-repo-create -- --repo=${handoff.repo}`;
  const queued = await queueCliRunnerJob({
    workspaceId: input.workspaceId ?? null,
    conversationId: input.conversationId ?? null,
    title: `App Forge repo create: ${handoff.appPlan.appName}`,
    command,
    kind: "app_forge_repo_create",
    riskLevel: "high",
    approvalText: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
    reason: `Create private starter repo ${handoff.repo} and push initial scaffold branch.`,
    metadata: { ...metadata, metadataEnv: encodeMetadata(metadata) },
  });
  return {
    ...queued,
    handoff,
    repo: handoff.repo,
    requiredApprovalPhrase: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
    safety: queued.ok ? "queued_only_no_local_execution_no_deploy_no_merge_no_schema_mutation" : "queue_failed_no_repo_created",
    nextAction: queued.ok ? "Run the trusted runner in execute mode to create the repo and push the initial scaffold branch." : "Fix the queue error, then retry.",
  };
}


export interface AppForgePreviewHandoffInput extends AppForgeRepoHandoffInput {
  repo?: string | null;
  branch?: string | null;
  owner?: string | null;
}

export interface AppForgePreviewHandoffResult {
  ok: boolean;
  appPlan: AppCreatorPlan;
  repo: string;
  branch: string;
  previewHandoff: {
    intent: "app_forge_preview_handoff";
    provider: "vercel";
    repo: string;
    branch: string;
    appName: string;
    slug: string;
    ready: boolean;
    requiredApprovalPhrase: string;
    commands: string[];
    checklist: string[];
    safety: string;
    preparedAt: string;
  };
  message: string;
  safety: string;
  nextAction: string;
}

function cleanBranchName(value?: string | null) {
  return (value || "initial-app-forge-scaffold")
    .replace(/[^A-Za-z0-9._/-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 120) || "initial-app-forge-scaffold";
}

export function createAppForgePreviewHandoff(input: AppForgePreviewHandoffInput): AppForgePreviewHandoffResult {
  const repoHandoff = createAppForgeRepoHandoff(input);
  const repo = input.repo && /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(input.repo)
    ? input.repo
    : repoHandoff.repo;
  const branch = cleanBranchName(input.branch);
  const preparedAt = new Date().toISOString();
  const commands = [
    `vercel link --repo ${repo}`,
    `vercel pull --yes --environment=preview`,
    `vercel build`,
    `vercel deploy --prebuilt --target=preview`,
  ];
  const checklist = [
    "Confirm the GitHub repo is private or intentionally public.",
    `Confirm branch ${branch} contains a passing build.` ,
    "Confirm no production environment variables are required for the preview.",
    "Confirm preview deployment is owner-review only before sharing.",
  ];
  return {
    ok: true,
    appPlan: repoHandoff.appPlan,
    repo,
    branch,
    previewHandoff: {
      intent: "app_forge_preview_handoff",
      provider: "vercel",
      repo,
      branch,
      appName: repoHandoff.appPlan.appName,
      slug: repoHandoff.appPlan.slug,
      ready: true,
      requiredApprovalPhrase: "APPROVE APP FORGE PREVIEW DEPLOY",
      commands,
      checklist,
      safety: "metadata_only_no_vercel_project_created_no_deploy_no_env_mutation_no_production_launch",
      preparedAt,
    },
    message: "App Forge v3 prepared a Vercel preview handoff only. No Vercel project, deployment, environment variable, merge, schema change, or production launch happened.",
    safety: "metadata_only_no_deploy_no_merge_no_schema_mutation_no_env_mutation",
    nextAction: "Review the handoff. A future approved runner job can execute the preview deployment with the exact preview approval phrase.",
  };
}
