import { buildAppCreatorPlan, type AppCreatorInput, type AppCreatorPlan } from "@/lib/app-creator";
import { queueCliRunnerJob } from "@/lib/cli-runner-jobs";

export type AppForgeCompletionTruth =
  | "handoff_only_no_repo_created"
  | "queued_not_executed_no_repo_created"
  | "queued_not_executed_no_preview_deployed"
  | "not_completed_yet_do_not_claim_app_created"
  | "repo_created_with_github_proof"
  | "preview_deployed_with_live_proof";

export interface AppForgeProofContract {
  completed: boolean;
  completionTruth: AppForgeCompletionTruth;
  completionEvidence: {
    repoUrl?: string | null;
    branch?: string | null;
    commitSha?: string | null;
    prUrl?: string | null;
    deploymentUrl?: string | null;
    verifiedAt?: string | null;
    missing: string[];
  };
}

function appForgeProofContract(completionTruth: AppForgeCompletionTruth, missing: string[], extra: Partial<AppForgeProofContract["completionEvidence"]> = {}): AppForgeProofContract {
  return {
    completed: false,
    completionTruth,
    completionEvidence: {
      repoUrl: null,
      branch: null,
      commitSha: null,
      prUrl: null,
      deploymentUrl: null,
      verifiedAt: new Date().toISOString(),
      ...extra,
      missing,
    },
  };
}

export interface AppForgeRepoHandoffInput extends AppCreatorInput {
  owner?: string | null;
  visibility?: "private" | "public";
}

export interface AppForgeRepoHandoffResult extends AppForgeProofContract {
  ok: boolean;
  appPlan: AppCreatorPlan;
  repo: string;
  repoName: string;
  visibility: "private" | "public";
  files: Array<{ path: string; purpose: string }>;
  commands: string[];
  safety: string;
  message: string;
  nextAction: string;
}

function cleanRepoName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "rune-generated-app";
}

function ownerOrDefault(owner?: string | null) {
  return (owner || process.env.RUNE_GITHUB_OWNER || "Tanjiro-1122").trim();
}

export function createAppForgeRepoHandoff(input: AppForgeRepoHandoffInput): AppForgeRepoHandoffResult {
  const appPlan = buildAppCreatorPlan(input);
  const repoName = cleanRepoName(input.repo?.split("/").pop() || appPlan.slug);
  const owner = ownerOrDefault(input.owner || input.repo?.split("/")[0]);
  const visibility = input.visibility || "private";
  const repo = `${owner}/${repoName}`;
  const folder = `generated/${repoName}`;

  const files = [
    { path: "package.json", purpose: "App scripts and dependencies" },
    { path: "src/App.tsx", purpose: "Generated starter UI" },
    { path: "src/main.tsx", purpose: "React entrypoint" },
    { path: "src/index.css", purpose: "Premium clean styling" },
    { path: "README.md", purpose: "Project description, safety notes, and next steps" },
  ];

  const commands = [
    `mkdir -p ${folder}`,
    `gh repo create ${repo} --${visibility} --description "${appPlan.appName} generated by Rune App Forge v1"`,
    `cd ${folder}`,
    "npm install",
    "npm run build",
    `git remote add origin git@github.com:${repo}.git`,
    "git checkout -b initial-app-forge-scaffold",
    "git add . && git commit -m \"Initial Rune App Forge scaffold\"",
    "git push -u origin initial-app-forge-scaffold",
  ];

  return {
    ok: true,
    ...appForgeProofContract("handoff_only_no_repo_created", ["github_repo", "branch", "commit_sha", "pr_url", "deployment_url"]),
    appPlan,
    repo,
    repoName,
    visibility,
    files,
    commands,
    safety: "repo_handoff_only_no_repo_created_no_files_written_no_deploy",
    message: "App Forge v1 prepared a new-repo handoff plan. It did not create a GitHub repo, write files, deploy, merge, mutate schemas, or touch production.",
    nextAction: "Approve a follow-up trusted runner job to create the repo and generate the scaffold, or ask Rune to refine the app plan first.",
  };
}


export const APP_FORGE_REPO_CREATE_APPROVAL_PHRASE = "APPROVE APP FORGE REPO CREATE";
export const APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE = "APPROVE APP FORGE PREVIEW DEPLOY";

export interface QueueAppForgeRepoCreateInput extends AppForgeRepoHandoffInput {
  approvalText: string;
  workspaceId?: string | null;
  conversationId?: string | null;
}

function encodeMetadata(metadata: Record<string, unknown>) {
  return Buffer.from(JSON.stringify(metadata), "utf8").toString("base64url");
}

export async function queueAppForgeRepoCreate(input: QueueAppForgeRepoCreateInput) {
  const handoff = createAppForgeRepoHandoff(input);
  if (input.approvalText !== APP_FORGE_REPO_CREATE_APPROVAL_PHRASE) {
    return {
      ok: false as const,
      ...appForgeProofContract("not_completed_yet_do_not_claim_app_created", ["approval", "github_repo", "branch", "commit_sha", "pr_url", "deployment_url"]),
      handoff,
      requiredApprovalPhrase: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
      error: "Exact approval phrase is required before queuing App Forge repo creation.",
      safety: "approval_required_no_repo_created_no_files_written_no_deploy",
    };
  }

  const metadata = {
    appForgeVersion: 2,
    repo: handoff.repo,
    repoName: handoff.repoName,
    visibility: handoff.visibility,
    appName: handoff.appPlan.appName,
    appPlan: handoff.appPlan,
    coreFeatures: handoff.appPlan.coreFeatures,
    screens: handoff.appPlan.screens,
    approval_text: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
    publicLaunch: false,
    deploy: false,
    merge: false,
    schemaMutation: false,
    paymentsChange: false,
    customerFacing: false,
    safety: "queued_repo_create_branch_push_no_deploy_no_merge_no_schema_mutation",
  };
  const command = `npm run app-forge-repo-create -- --repo=${handoff.repo}`;
  const queued = await queueCliRunnerJob({
    workspaceId: input.workspaceId ?? null,
    conversationId: input.conversationId ?? null,
    title: `App Forge repo create: ${handoff.appPlan.appName}`,
    command,
    kind: "app_forge_repo_create",
    riskLevel: "high",
    approvalText: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
    reason: `Create private starter repo ${handoff.repo} and push initial scaffold branch.`,
    metadata: { ...metadata, metadataEnv: encodeMetadata(metadata) },
  });
  return {
    ...queued,
    ...appForgeProofContract("queued_not_executed_no_repo_created", ["runner_execution", "github_repo_verification", "branch_verification", "commit_sha", "pr_url", "deployment_url"], { repoUrl: `https://github.com/${handoff.repo}` }),
    handoff,
    repo: handoff.repo,
    requiredApprovalPhrase: APP_FORGE_REPO_CREATE_APPROVAL_PHRASE,
    safety: queued.ok ? "queued_only_no_local_execution_no_deploy_no_merge_no_schema_mutation" : "queue_failed_no_repo_created",
    nextAction: queued.ok ? "Run the trusted runner in execute mode to create the repo and push the initial scaffold branch." : "Fix the queue error, then retry.",
  };
}


export interface AppForgePreviewHandoffInput extends AppForgeRepoHandoffInput {
  repo?: string | null;
  branch?: string | null;
  owner?: string | null;
}

export interface AppForgePreviewHandoffResult extends AppForgeProofContract {
  ok: boolean;
  appPlan: AppCreatorPlan;
  repo: string;
  branch: string;
  previewHandoff: {
    intent: "app_forge_preview_handoff";
    provider: "vercel";
    repo: string;
    branch: string;
    appName: string;
    slug: string;
    ready: boolean;
    requiredApprovalPhrase: string;
    commands: string[];
    checklist: string[];
    safety: string;
    preparedAt: string;
  };
  message: string;
  safety: string;
  nextAction: string;
}

function cleanBranchName(value?: string | null) {
  return (value || "initial-app-forge-scaffold")
    .replace(/[^A-Za-z0-9._/-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 120) || "initial-app-forge-scaffold";
}

export function createAppForgePreviewHandoff(input: AppForgePreviewHandoffInput): AppForgePreviewHandoffResult {
  const repoHandoff = createAppForgeRepoHandoff(input);
  const repo = input.repo && /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(input.repo)
    ? input.repo
    : repoHandoff.repo;
  const branch = cleanBranchName(input.branch);
  const preparedAt = new Date().toISOString();
  const commands = [
    `vercel link --repo ${repo}`,
    `vercel pull --yes --environment=preview`,
    `vercel build`,
    `vercel deploy --prebuilt --target=preview`,
  ];
  const checklist = [
    "Confirm the GitHub repo is private or intentionally public.",
    `Confirm branch ${branch} contains a passing build.` ,
    "Confirm no production environment variables are required for the preview.",
    "Confirm preview deployment is owner-review only before sharing.",
  ];
  return {
    ok: true,
    ...appForgeProofContract("handoff_only_no_repo_created", ["github_repo_verification", "branch_verification", "preview_deployment_url"], { repoUrl: `https://github.com/${repo}`, branch }),
    appPlan: repoHandoff.appPlan,
    repo,
    branch,
    previewHandoff: {
      intent: "app_forge_preview_handoff",
      provider: "vercel",
      repo,
      branch,
      appName: repoHandoff.appPlan.appName,
      slug: repoHandoff.appPlan.slug,
      ready: true,
      requiredApprovalPhrase: APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE,
      commands,
      checklist,
      safety: "metadata_only_no_vercel_project_created_no_deploy_no_env_mutation_no_production_launch",
      preparedAt,
    },
    message: "App Forge v3 prepared a Vercel preview handoff only. No Vercel project, deployment, environment variable, merge, schema change, or production launch happened.",
    safety: "metadata_only_no_deploy_no_merge_no_schema_mutation_no_env_mutation",
    nextAction: "Review the handoff. A future approved runner job can execute the preview deployment with the exact preview approval phrase.",
  };
}


export interface QueueAppForgePreviewDeployInput extends AppForgePreviewHandoffInput {
  approvalText: string;
  workspaceId?: string | null;
  conversationId?: string | null;
}

export async function queueAppForgePreviewDeploy(input: QueueAppForgePreviewDeployInput) {
  const handoff = createAppForgePreviewHandoff(input);
  if (input.approvalText !== APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE) {
    return {
      ok: false as const,
      ...appForgeProofContract("not_completed_yet_do_not_claim_app_created", ["approval", "preview_deployment_url"], { repoUrl: `https://github.com/${handoff.repo}`, branch: handoff.branch }),
      handoff,
      requiredApprovalPhrase: APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE,
      error: "Exact approval phrase is required before queuing App Forge preview deployment.",
      safety: "approval_required_no_preview_deploy_no_env_mutation_no_production_launch",
    };
  }
  const metadata = {
    appForgeVersion: 4,
    repo: handoff.repo,
    branch: handoff.branch,
    appName: handoff.appPlan.appName,
    appPlan: handoff.appPlan,
    approval_text: APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE,
    previewOnly: true,
    target: "preview",
    production: false,
    publicLaunch: false,
    merge: false,
    schemaMutation: false,
    paymentsChange: false,
    envMutation: false,
    customerFacing: false,
    safety: "queued_preview_deploy_only_no_production_no_merge_no_env_or_schema_mutation",
  };
  const command = `npm run app-forge-preview-deploy -- --repo=${handoff.repo} --branch=${handoff.branch}`;
  const queued = await queueCliRunnerJob({
    workspaceId: input.workspaceId ?? null,
    conversationId: input.conversationId ?? null,
    title: `App Forge preview deploy: ${handoff.appPlan.appName}`,
    command,
    kind: "app_forge_preview_deploy",
    riskLevel: "high",
    approvalText: APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE,
    reason: `Create a Vercel preview deployment for ${handoff.repo}@${handoff.branch}.`,
    metadata: { ...metadata, metadataEnv: encodeMetadata(metadata) },
  });
  return {
    ...queued,
    ...appForgeProofContract("queued_not_executed_no_preview_deployed", ["runner_execution", "deployment_url", "live_smoke"], { repoUrl: `https://github.com/${handoff.repo}`, branch: handoff.branch }),
    handoff,
    repo: handoff.repo,
    branch: handoff.branch,
    requiredApprovalPhrase: APP_FORGE_PREVIEW_DEPLOY_APPROVAL_PHRASE,
    safety: queued.ok ? "queued_only_no_local_execution_preview_only_no_production" : "queue_failed_no_preview_deploy",
    nextAction: queued.ok ? "Run the trusted runner in execute mode to create the preview deployment." : "Fix the queue error, then retry.",
  };
}


export interface VerifyAppForgeRunnerResultInput {
  kind: "repo_create" | "preview_deploy";
  repo: string;
  branch?: string | null;
  commitSha?: string | null;
  prUrl?: string | null;
  deploymentUrl?: string | null;
  liveSmokeOk?: boolean | null;
  runnerTaskId?: string | null;
  runnerStatus?: string | null;
}

function normalizeRepoUrl(repo: string) {
  const normalized = repo.replace(/^https?:\/\/github\.com\//i, "").replace(/\.git$/i, "");
  return `https://github.com/${normalized}`;
}

function validGithubRepoSlug(repo: string) {
  return /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(repo.replace(/^https?:\/\/github\.com\//i, "").replace(/\.git$/i, ""));
}

function validGithubPrUrl(prUrl?: string | null) {
  return !prUrl || /^https:\/\/github\.com\/[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+\/pull\/\d+$/i.test(prUrl);
}

function validCommitSha(commitSha?: string | null) {
  return Boolean(commitSha && /^[a-f0-9]{7,40}$/i.test(commitSha));
}

function validDeploymentUrl(deploymentUrl?: string | null) {
  return Boolean(deploymentUrl && /^https:\/\//i.test(deploymentUrl));
}

export function verifyAppForgeRunnerResult(input: VerifyAppForgeRunnerResultInput): AppForgeProofContract & {
  ok: boolean;
  kind: VerifyAppForgeRunnerResultInput["kind"];
  repo: string;
  branch?: string | null;
  runnerTaskId?: string | null;
  runnerStatus?: string | null;
  message: string;
  safety: string;
} {
  const repo = input.repo.replace(/^https?:\/\/github\.com\//i, "").replace(/\.git$/i, "");
  const missing: string[] = [];
  if (!validGithubRepoSlug(repo)) missing.push("github_repo_verification");
  if (!input.branch) missing.push("branch_verification");
  if (!validCommitSha(input.commitSha)) missing.push("commit_sha");
  if (!validGithubPrUrl(input.prUrl)) missing.push("valid_pr_url");

  if (input.kind === "preview_deploy") {
    if (!validDeploymentUrl(input.deploymentUrl)) missing.push("deployment_url");
    if (input.liveSmokeOk !== true) missing.push("live_smoke");
  }

  const completed = missing.length === 0;
  const completionTruth: AppForgeCompletionTruth = completed
    ? input.kind === "repo_create"
      ? "repo_created_with_github_proof"
      : "preview_deployed_with_live_proof"
    : input.kind === "repo_create"
      ? "queued_not_executed_no_repo_created"
      : "queued_not_executed_no_preview_deployed";

  return {
    ok: true,
    kind: input.kind,
    repo,
    branch: input.branch || null,
    runnerTaskId: input.runnerTaskId || null,
    runnerStatus: input.runnerStatus || null,
    completed,
    completionTruth,
    completionEvidence: {
      repoUrl: normalizeRepoUrl(repo),
      branch: input.branch || null,
      commitSha: input.commitSha || null,
      prUrl: input.prUrl || null,
      deploymentUrl: input.deploymentUrl || null,
      verifiedAt: new Date().toISOString(),
      missing,
    },
    message: completed
      ? input.kind === "repo_create"
        ? "App Forge runner result verified: GitHub repo, branch, commit SHA, and optional PR URL proof are present."
        : "App Forge preview runner result verified: deployment URL and live smoke proof are present."
      : `App Forge runner result is not complete. Missing proof: ${missing.join(", ")}. Do not claim the app/repo/deployment is complete.`,
    safety: "verification_only_no_repo_no_deploy_no_schema_payment_dns_customer_mutation",
  };
}
